### ISSUE TITLE
Use constants instead of magic variables

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#1]
https://github.com/robtweed/ewd-document-store/blob/55179cb34490bb63f8d086d93d40b647c98cc960/lib/proto/getDocument.js#L96

http://docs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=BXJS_globals#BXJS_globals_data

**Comment by robtweed** [comment]
Will be changed in next build

**Comment by killmenot** [comment]
done via https://github.com/robtweed/ewd-document-store/commit/593e9765749e2b3596b186b4dcd8e0d3ad7378d5
