### ISSUE TITLE
Looks like bug in countChildren

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#13]
@robtweed have a question,
<img width="417" alt="screenshot 2017-09-11 18 31 02" src="https://user-images.githubusercontent.com/119337/30293847-8cf6e4d8-9743-11e7-98cf-d5f3fabe43cf.png">

What should be the result value here? getDocument returns
```
{ bar: 'barValue', baz: 'bazValue', foo: 'fooValue' }
```

I have a feeling that this line
https://github.com/robtweed/ewd-document-store/blob/master/lib/proto/count.js#L39
should be replace to
if (node.result !== '') count++;

**Comment by robtweed** [comment]
Yes you're correct!  Will be fixed in next build. Thanks for finding this!

**Comment by killmenot** [comment]
I included the bugfix in PR #15

**Comment by robtweed** [comment]
Ah ok, thanks!
