### ISSUE TITLE
unused variable?

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#2]
https://github.com/robtweed/ewd-document-store/blob/55179cb34490bb63f8d086d93d40b647c98cc960/lib/proto/value.js#L45

**Comment by robtweed** [comment]
Good find - will be fixed in next build

**Comment by killmenot** [comment]
done via https://github.com/robtweed/ewd-document-store/commit/593e9765749e2b3596b186b4dcd8e0d3ad7378d5
