### ISSUE TITLE
Declare variable FIELD_MARK instead of using String.fromCharCode(254)

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#5]
https://github.com/robtweed/ewd-document-store/blob/55179cb34490bb63f8d086d93d40b647c98cc960/lib/proto/forEach.js#L72

**Comment by robtweed** [comment]
OK - will be in next build

**Comment by killmenot** [comment]
done via https://github.com/robtweed/ewd-document-store/commit/593e9765749e2b3596b186b4dcd8e0d3ad7378d5
