### ISSUE TITLE
Quit logic differences between forEachChild and forEachLeafNode

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#6]
#### forEachChild
https://github.com/robtweed/ewd-document-store/blob/master/lib/proto/forEach.js#L123-L124
quit if callback returns true

#### forEachLeafNode
https://github.com/robtweed/ewd-document-store/blob/master/lib/proto/forEachLeafNode.js#L61-L62
quit if callback returns false

I think it should be the same

**Comment by robtweed** [comment]
I think you are correct - should be
if (quit === true) ok = false;
