### ISSUE TITLE
does it modify original variable?

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#8]
https://github.com/robtweed/ewd-document-store/blob/55179cb34490bb63f8d086d93d40b647c98cc960/lib/proto/setDocument.js#L44

**Comment by robtweed** [comment]
This logic is needed for certain very particular situations.  Yes it deliberately overwrites the original with an empty string, as global storage can't store undefined or null - in the Mumps language, the empty string is effectively regarded as "null"
