### ISSUE TITLE
rename base to offset

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#9]
https://github.com/robtweed/ewd-document-store/blob/55179cb34490bb63f8d086d93d40b647c98cc960/lib/proto/getDocument.js#L39

Having the same variable name that setDocument is

**Comment by robtweed** [comment]
Good idea - will be done in next build

**Comment by killmenot** [comment]
done via https://github.com/robtweed/ewd-document-store/commit/593e9765749e2b3596b186b4dcd8e0d3ad7378d5
